### ISSUE TITLE
This user is privacy hacker, collect data and sell it

### ISSUE THREAD

**Issue by Zulu-1540** [hisi-oss/android_device_huawei_hi6250-9-common#4]
https://github.com/snowplow/snowplow-javascript-tracker/blob/743e77df8bf914682017e350469b99c22207505f/plugins%2Fbrowser-plugin-button-click-tracking%2Fsrc%2Fapi.ts#L82-L83

**Comment by isaackogan** [comment]
are you mentally deficient @Zulu-1540
